/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

// ▼▼▼ 1. 記得這裡要解構出 { config } ▼▼▼
export function Model({ config, ...props }) {
  const { nodes, materials } = useGLTF('/motorcycle.glb')

  // ▼▼▼ 2. 定義變色材質 (從其他檔案複製過來的) ▼▼▼
  const CarPaintMaterial = (
    <meshPhysicalMaterial 
      color={config?.color || "#0066cc"} 
      metalness={config?.metalness ?? 0.6}
      roughness={config?.roughness ?? 0.2}
      clearcoat={config?.clearcoat ?? 1.0}
      clearcoatRoughness={config?.clearcoatRoughness ?? 0.1}
      iridescence={config?.iridescence ?? 0}
      envMapIntensity={1.5}
    />
  )

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={10.13}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              
              {/* 非車殼部位維持原樣 */}
              <mesh geometry={nodes.Object_10.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_13.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_16.geometry} material={materials['red.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_19.geometry} material={materials['white.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_22.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_25.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_28.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_31.geometry} material={materials['chrome.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              
              {/* ▼▼▼ 修改 1：副車漆 (原本是 carpaint_second.001) ▼▼▼ */}
              <mesh geometry={nodes.Object_34.geometry} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1}>
                {CarPaintMaterial}
              </mesh>

              <mesh geometry={nodes.Object_37.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              
              {/* ▼▼▼ 修改 2：主車漆 (原本是 carpaint.001) ▼▼▼ */}
              <mesh geometry={nodes.Object_40.geometry} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1}>
                {CarPaintMaterial}
              </mesh>

              {/* 中間省略很多很多零件，維持原樣 */}
              <mesh geometry={nodes.Object_43.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_46.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_49.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_52.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_55.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_58.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_61.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_64.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_67.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_70.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_73.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_76.geometry} material={materials['gold.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_79.geometry} material={materials['brakedisk.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_82.geometry} material={materials['brakedisk.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_85.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_88.geometry} material={materials['gray.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_91.geometry} material={materials['red.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_94.geometry} material={materials['gray.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_97.geometry} material={materials['gray.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_100.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_103.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_106.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_109.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_112.geometry} material={materials['white.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_115.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              
              {/* ▼▼▼ 修改 3：另一塊主車漆 (原本是 carpaint.001) ▼▼▼ */}
              <mesh geometry={nodes.Object_118.geometry} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1}>
                {CarPaintMaterial}
              </mesh>

              {/* ▼▼▼ 修改 4：藍色區塊 (原本是 blue.001) ▼▼▼ */}
              <mesh geometry={nodes.Object_121.geometry} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1}>
                {CarPaintMaterial}
              </mesh>

              <mesh geometry={nodes.Object_124.geometry} material={materials['red.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_127.geometry} material={materials['red.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_130.geometry} material={materials['red.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_133.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_136.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_139.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_142.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_145.geometry} material={materials['chrome.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_148.geometry} material={materials['gold.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_151.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_154.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_157.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_160.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_163.geometry} material={materials['gray.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_166.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              
              {/* ▼▼▼ 修改 5：另一塊副車漆 (原本是 carpaint_second.001) ▼▼▼ */}
              <mesh geometry={nodes.Object_169.geometry} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1}>
                {CarPaintMaterial}
              </mesh>

              {/* 剩下的零件全部維持原樣 */}
              <mesh geometry={nodes.Object_172.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_175.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_178.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_181.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_184.geometry} material={materials['chrome.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_187.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_190.geometry} material={materials['clearglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_193.geometry} material={materials['clearglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_196.geometry} material={materials['clearglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_199.geometry} material={materials['clearglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_202.geometry} material={materials['clearglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_205.geometry} material={materials['redglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_208.geometry} material={materials['clearglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_211.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_214.geometry} material={materials['clearglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_217.geometry} material={materials['orangeglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_220.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_223.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_226.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_229.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_232.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_235.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <group position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1}>
                <mesh geometry={nodes.Object_238.geometry} material={materials['LicPlate_black.001']} />
                <mesh geometry={nodes.Object_240.geometry} material={materials['LicPlate_white.001']} />
              </group>
              <mesh geometry={nodes.Object_243.geometry} material={materials['clearglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_246.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_249.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_252.geometry} material={materials['gray.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_255.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_258.geometry} material={materials['mirror.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_261.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_264.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_267.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_270.geometry} material={materials['bronze.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_273.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_276.geometry} material={materials['orangeglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_279.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_282.geometry} material={materials['chrome.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_285.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_288.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_291.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_294.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_297.geometry} material={materials['white.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_300.geometry} material={materials['white.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_303.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_306.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_309.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_312.geometry} material={materials['chrome.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_315.geometry} material={materials['chrome.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_318.geometry} material={materials['chrome.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_321.geometry} material={materials['chrome.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_324.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_327.geometry} material={materials['clearglass.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_330.geometry} material={materials['rim_second.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_333.geometry} material={materials['rim_second.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_336.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_339.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_342.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_345.geometry} material={materials['gold.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_348.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_351.geometry} material={materials['red.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_354.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_357.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_360.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_363.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_366.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_369.geometry} material={materials['black.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_372.geometry} material={materials['gray.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_375.geometry} material={materials['red.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_378.geometry} material={materials['white.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_381.geometry} material={materials['white.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_384.geometry} material={materials['tire.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_387.geometry} material={materials['tire.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_390.geometry} material={materials['mattemetal.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
              <mesh geometry={nodes.Object_393.geometry} material={materials['bronze.001']} position={[-0.727, 0.036, -0.057]} rotation={[0.862, 1.566, 2.275]} scale={0.1} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/motorcycle.glb')