/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ config, ...props }) {
const { nodes, materials } = useGLTF('./yamaha_yzf-r3_2017.glb')

  // 定義變色材質
  const CarPaintMaterial = (
    <meshPhysicalMaterial 
      color={config?.color || "#0066cc"} 
      metalness={config?.metalness ?? 0.6}
      roughness={config?.roughness ?? 0.2}
      clearcoat={config?.clearcoat ?? 1.0}
      clearcoatRoughness={config?.clearcoatRoughness ?? 0.1}
      iridescence={config?.iridescence ?? 0}
      iridescenceIOR={1.6}
      iridescenceThicknessRange={[100, 400]}
      envMapIntensity={1.5}
    />
  )

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        
        {/* 第一組：把這裡的 simetrico_7 改回原本的藍色 (metal_azul) */}
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.simetrico_0.geometry} material={materials.caucho_brillante} />
          <mesh geometry={nodes.simetrico_2.geometry} material={materials.plastico_negro} />
          <mesh geometry={nodes.simetrico_5.geometry} material={materials.ALUMINIO_negro} />
          <mesh geometry={nodes.simetrico_6.geometry} material={materials['plastico_negro.001']} />
          <mesh geometry={nodes.simetrico_4.geometry} material={materials.luces_rojas} />
          <mesh geometry={nodes.simetrico_7.geometry} material={materials.metal_azul} /> 
          <mesh geometry={nodes.simetrico_3.geometry} material={materials.aluminio_blanco} />
        </group>

        {/* 第二組：把這裡的 no_simetrico_5 改回原本的藍色 */}
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.no_simetrico_0.geometry} material={materials.plastico_negro} />
          <mesh geometry={nodes.no_simetrico_1.geometry} material={materials.aluminio_blanco} />
          <mesh geometry={nodes.no_simetrico_2.geometry} material={materials.ALUMINIO_negro} />
          <mesh geometry={nodes.no_simetrico_3.geometry} material={materials.plastico_blanco} />
          <mesh geometry={nodes.no_simetrico_4.geometry} material={materials.caucho_brillante} />
          <mesh geometry={nodes.no_simetrico_5.geometry} material={materials.metal_azul} />
        </group>

        {/* ...前輪組省略，維持原樣... */}
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.neumatico_delantero001_0.geometry} material={materials.caucho_brillante} />
          <mesh geometry={nodes.neumatico_delantero001_1.geometry} material={materials.luces_rojas} />
        </group>

        {/* ▼▼▼ 重點在這裡：Carenaje (整流罩) ▼▼▼ */}
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.carenaje_0.geometry} material={materials.caucho_brillante} />
          
          {/* 👇 把它換成我們的變色材質！(原本是 aluminio_blanco) */}
          <mesh geometry={nodes.carenaje_1.geometry}>
            {CarPaintMaterial}
          </mesh>

          <mesh geometry={nodes.carenaje_2.geometry} material={materials.plastico_negro} />
          <mesh geometry={nodes.carenaje_3.geometry} material={materials.ALUMINIO_negro} />
          <mesh geometry={nodes.carenaje_4.geometry} material={materials['plastico_negro.001']} />
        </group>

        {/* ...以下維持原樣... */}
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.neumatico_delantero009_0.geometry} material={materials.caucho_brillante} />
          <mesh geometry={nodes.neumatico_delantero009_1.geometry} material={materials.aluminio_blanco} />
        </group>
        <mesh geometry={nodes.neumatico_delantero002_0.geometry} material={materials.ALUMINIO_negro} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.neumatico_delantero004_0.geometry} material={materials.aluminio_blanco} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.neumatico_delantero005_0.geometry} material={materials.vidrio} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.guarda_cadena001_0.geometry} material={materials.plastico_blanco} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.neumatico_delantero007_0.geometry} material={materials.aluminio_blanco} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.neumatico_delantero008_0.geometry} material={materials.vidrio} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/yamaha_yzf-r3_2017.glb')